config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pets do
    member do
      get :modal
    end
  end
  resources :orders, only: [:index, :show, :new, :create, :destroy]

  root to: "pets#index"

  get 'users/orders/new/:pet_id', to: 'orders#new', as: 'new_user_order'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
 <div class="footer mt-5">

    <div class="row-footer">
      <div class="col-footer logo-container">
        <%= image_tag "adoptpet-logo.png", alt: "Logo", class: "footer-image" %>
      </div>

      <div class="col-footer">
        <h3>Menu</h3>
          <li><a href="#">Quero adotar</a></li>
          <li><a href="#">Quero doar</a></li>
          <li><a href="#">Login</a></li>
          <li><a href="#">Cadastre-se</a></li>
      </div>

      <div class="col-footer">
        <h3>Siga a AdoptPet</h3>
        <div class="footer-links">
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
        </div>
      </div>

      <div class="col-footer">
        <h3>Cadastre-se e receba novidades</h3>
        <form action="#" method="post" class="newsletter-form">
          <input type="email" name="email" placeholder="Informe seu e-mail" required>
          <label>
            <input type="checkbox" name="privacy-policy" required>
            Li e aceito as <a href="#"><strong> políticas de privacidade</strong></a>
          </label>
          <div class="footer-btn" type="submit">Enviar</div>
        </form>

      </div>
    </div>
  </div>

app/views/shared/_index-banner.html.erb
<div class="index-banner-wrapper">
  <%= image_tag "index-banner.png", alt: "Banner", class: "index-banner-image" %>
  <div class="index-banner-overlay d-flex align-items-center">
    <div class="container">
      <h2 class="banner-overlay-text txt-margin" data-controller="counter">
        <span class="counter-number" data-counter-target="counter">500</span> bichinhos já encontraram um lar.
        <br>Adote um Pet! <br>
      </h2>
      <div class="btn btn-primary-orange txt-margin">Descubra seu pet perfeito</div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "shield-dog-solid.svg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    🐾</button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Quero adotar", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Quero doar", new_pet_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Mensagens", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Pedidos", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://avatars.githubusercontent.com/u/194866677?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
              <%# link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_newnav.html.erb
<nav class="navbar">
  <div class="navbar-left">
    <%= link_to root_path, class: "navbar-left-link" do %>
      <i class="fa-solid fa-bars logo-icon"></i>
      <span class="navbar-brand">AdoptPet</span>
    <% end %>
  </div>

  <div class="navbar-center">
    <%= link_to root_path, class: "navbar-center-link" do %>
      <i class="fa-solid fa-paw logo-icon-center"></i>
    <% end %>
  </div>

  <div class="navbar-right">
    <% if user_signed_in? %>
      <a href="<%= new_pet_path %>" class="nav-link">Quero Doar</a>
      <a href="<%= root_path %>" class="nav-link bold">Quero Adotar</a>

      <div class="dropdown">
        <% if current_user.avatar.attached? %>
          <%= cl_image_tag current_user.avatar.key,
            transformation: [{ width: 300, height: 300, crop: "fill" }],
            alt: "Avatar",
            class: "avatar dropdown-toggle",
            id: "navbarDropdown",
            data: { bs_toggle: "dropdown" },
            'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <img src="https://res.cloudinary.com/dq7l8216n/image/upload/v1633660004/adoptpet/avatar-placeholder.png" alt="Avatar" class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <% end %>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <%= link_to "Minhas Adoções", orders_path, class: "dropdown-item" %>
          <%= link_to "Meu Perfil", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "Sair", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item text-danger" %>
        </div>
      </div>

    <% else %>
      <a href="<%= new_user_session_path %>" class="nav-link">Entrar <i class="fa-solid fa-arrow-right primary-orange"></i></a>
      <a href="<%= new_user_registration_path %>" class="nav-link bold">Cadastre-se</a>
    <% end %>
  </div>
</nav>
<hr class="navbar-separator">

app/views/shared/_pet.html.erb
<div class="pet">
  <h2><%= pet.name %></h2>
  <p>Idade: <%= pet.age %> anos</p>
  <p>Animal: <%= pet.species %></p>
</div>